### ISSUE TITLE
where is the "FaceSeg.sln"

### ISSUE THREAD

**Issue by weiyuxingchen** [YexingWan/Fast-Portrait-Segmentation#2]

**Comment by enjustli** [comment]
you can use cmake gui to gen this.

**Comment by YexingWan** [comment]
We provide the cmakelist file for multi-platform build. If you want to build by VS, just use cmake to generate sln file and load the project in VS. For the way to generate sln by cmake on Windows, Don't forget to provide MNN_INCLUDE_DIRS and MNN_LIBRARY_DIRS when generate. We will update README as soon :>
