### ISSUE TITLE
Sinet training code and dataset

### ISSUE THREAD

**Issue by ilwoonam75** [YexingWan/Fast-Portrait-Segmentation#3]
Thank you for your repository.
Can you share your training code and dataset?
If not, can you explain how to train sinet?

**Comment by YexingWan** [comment]
Sorry for slow reply. 
Here is the origin SINet implementation https://github.com/clovaai/ext_portrait_segmentation  
Further, the paper link is also provided in readme. 
The weight file provided is the original trained weight in origin SINet implementation after conversion (.pth -> .onnx -> .mnn)
The training dataset is EG1800 and an augmentation dataset generated by Baidu's DeepFashion dataset. The way to do dataAug can be found in paper as well.
You can learn the way to train SINet by code and paper as well. 
Thank you for your question
