### ISSUE TITLE
ValueError: cannot reshape array of size 40960 into shape (1,2,160,256)

### ISSUE THREAD

**Issue by kiyse** [YexingWan/Fast-Portrait-Segmentation#4]
file : runIE.py
model : Dnc_SINet_bi_256_160.mnn
result = (np.reshape(result,(-1,4))[:,:2]).T.reshape(out_shape)
ValueError: cannot reshape array of size 40960 into shape (1,2,160,256)
Is [:,:2] right?

**Comment by kiyse** [comment]
@enjustli @YexingWan

**Comment by YexingWan** [comment]
Could you please show more info to us such as your input size or shape of result?
As 256*160=40960, and the ValueError is not from [:,:2], which indexing and output array with shape, i guess, (20480,2). The 20480 is result h * result w, which should be same as input h and imput w.
So i guess the input size of image might be wrong.
Feel free to ask  : >

**Comment by zengchan** [comment]
I I have the same problem, I don't know how to solve it.@YexingWan

**Comment by zengchan** [comment]
My input_tensor is (256,320,3) and the model I use is Dnc_SINet_bi_320_256.mnn, the result shape is 1,2,256,320,when I run cam_seg.py, the line " (np.reshape(result, (-1, 4)))[:, :2].T.reshape(output_shape)" will be wrong, the output shape is (1,2,256,320) Can you help me solve it, thank you very much.
